name:                LambDEC
version:             0.1.0.0
github:              "githubuser/LambDEC"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/LambDEC#readme>

dependencies:
- base >= 4.7 && < 5
- dhall
- text
- vector
- vector-sized
- lens
- tasty
- tasty-hunit
- tasty-quickcheck
- generic-monoid
- vector-space
- refined

library:
  source-dirs: src

executables:
  LambDEC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambDEC

tests:
  LambDEC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambDEC
  LambDEC-tasty:
    main: Tasty.hs
    source-dirs: test-tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambDEC
    - tasty
    - tasty-hunit
    - tasty-quickcheck