name: formulative
version: 0.1.0.0
github: "githubuser/formulative"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/formulative#readme>

dependencies:
  - ad
  - aeson
  - attoparsec
  - base >= 4.7 && < 5
  - base-noprelude
  - bytestring
  - cassava
  - constraints
  - containers
  - dhall
  - eigen
  - exact-combinatorics
  - finite-field
  - fused-effects
  - ghc-prim
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - hashable
  - lens
  - matrix-sized
  - megaparsec
  - numeric-limits
  - Only
  - optparse-applicative
  - path
  - path-io
  - physics
  - prettyprinter
  - refined
  - reflection
  - replace-megaparsec
  - rio
  - finite-typelits
  - safe-exceptions
  - scientific
  - simple-reflect
  - turtle
  - singletons
  - string-conversions
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - template-haskell
  - text
  - unordered-containers
  - vector
  - vector-algorithms
  - vector-sized
# - time
# - typenums
# - vector-space

library:
  source-dirs: src
  other-modules:
    - CustomPrelude

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
# - RebindableSyntax

executables:
  preprocess:
    main: Preprocess.hs
    other-modules: []
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - formulative

tests:
  formulative-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - formulative
  formulative-tasty:
    main: Tasty.hs
    source-dirs: test-tasty
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - formulative
      - tasty
      - tasty-hunit
      - tasty-quickcheck

benchmarks:
  Factorial:
    main: Factorial.hs
    source-dirs: benchmarks/Factorial
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - formulative
      - criterion
  StackingEffects:
    main: StackEffects.hs
    source-dirs: benchmarks/FusedEffects
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - formulative
      - criterion
  MatrixMul:
    main: MatrixMul.hs
    source-dirs: benchmarks/MatrixMul
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - formulative
      - criterion
  MatrixToVector:
    main: MatrixToVector.hs
    source-dirs: benchmarks/MatrixToVector
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - formulative
      - criterion
  UnsafeIndex:
    main: UnsafeIndex.hs
    source-dirs: benchmarks/UnsafeIndex
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - formulative
      - criterion
