name:                hstructure
version:             0.1.0.0
github:              "githubuser/hstructure"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hstructure#readme>

dependencies:
- base >= 4.7 && < 5
- dhall
- text
- vector
- vector-sized
- lens
- tasty
- tasty-hunit
- tasty-quickcheck
- vector-space
- refined
- HList
- reflection
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-prim
- safe-exceptions
- matrix-sized
- eigen
- containers
- exact-combinatorics
- simple-reflect

library:
  source-dirs: src

executables:
  hstructure-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstructure

tests:
  hstructure-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstructure
  hstructure-tasty:
    main: Tasty.hs
    source-dirs: test-tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstructure
    - tasty
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  criterion:
    main: Criterion.hs
    source-dirs: benchmark-criterion
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstructure
    - criterion