name: formulative-matrix
version: 0.1.0.0
github: "githubuser/formulative-matrix"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/formulative-matrix#readme>

dependencies:
  - formulative
  - ad
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - cassava
  - constraints
  - containers
  - conduit
  - cryptonite
  - dhall
  - exact-combinatorics
  - fused-effects
  - ghc-prim
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - hashable
  - hmatrix
  - ieee
  - matrix-sized
  - megaparsec
  - numeric-limits
  - optparse-applicative
  - path
  - path-io
  - physics
  - prettyprinter
  - refined
  - replace-megaparsec
  - safe-exceptions
  - scientific
  - simple-reflect
  - singletons
  - string-conversions
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - template-haskell
  - text
  - time
  - unordered-containers
  - vector
  - vector-algorithms
  - vector-sized
library:
  source-dirs: src

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

tests:
  formulative-matrix-tasty:
    main: Tasty.hs
    source-dirs: test-tasty
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O0
    dependencies:
      - formulative
      - formulative-matrix
      - tasty
      - tasty-hunit
      - tasty-quickcheck

benchmarks:
  MatrixMul:
    main: MatrixMul.hs
    source-dirs: benchmarks/MatrixMul
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O1
    dependencies:
      - formulative
      - criterion
  MatrixToVector:
    main: MatrixToVector.hs
    source-dirs: benchmarks/MatrixToVector
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O1
    dependencies:
      - formulative
      - criterion
  UnsafeIndex:
    main: UnsafeIndex.hs
    source-dirs: benchmarks/UnsafeIndex
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O1
    dependencies:
      - formulative
      - criterion
