name:                formulative-algebra
version:             0.1.0.0
github:              "ccycle/formulative-algebra"
license:             BSD3
author:              "ccycle"
maintainer:          "ccycle713@gmail.com"
copyright:           "2023 ccycle"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ccycle/formulative-algebra#readme>

dependencies:
- ad
- base >= 4.7 && < 5
- scientific
- refined
- simple-reflect
- safe-exceptions
- vector
- minimal-default
- hashable
- fused-effects
- dhall
- vector-algorithms
- vector-sized
- containers

ghc-options:
- -Wall
- -Werror=missing-methods
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingVia
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- RebindableSyntax
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

tests:
  test:
    main:                Tasty.hs
    source-dirs:         test
    default-extensions:
    - NoRebindableSyntax
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - formulative-algebra
    - tasty
    - tasty-hunit
    - tasty-quickcheck
